[2025-04-10T01:59:25.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2025-04-10T01:59:23.320007+00:00 [queued]>
[2025-04-10T01:59:25.854+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_data manual__2025-04-10T01:59:23.320007+00:00 [queued]>
[2025-04-10T01:59:25.855+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-10T01:59:25.925+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_data> on 2025-04-10 01:59:23.320007+00:00
[2025-04-10T01:59:25.931+0000] {standard_task_runner.py:57} INFO - Started process 256 to run task
[2025-04-10T01:59:25.935+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_data', 'manual__2025-04-10T01:59:23.320007+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmphfmk4_zc']
[2025-04-10T01:59:25.937+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract_data
[2025-04-10T01:59:26.047+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.extract_data manual__2025-04-10T01:59:23.320007+00:00 [running]> on host 40127fbc9741
[2025-04-10T01:59:26.208+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T01:59:23.320007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T01:59:23.320007+00:00'
[2025-04-10T01:59:29.634+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/pyarrow/pandas_compat.py:373 FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
[2025-04-10T01:59:30.377+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 14, in extract
    df.to_parquet(PARQUET_PATH, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 2973, in to_parquet
    return to_parquet(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 483, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 197, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/datasets/df.parquet'
[2025-04-10T01:59:30.397+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract_data, execution_date=20250410T015923, start_date=20250410T015925, end_date=20250410T015930
[2025-04-10T01:59:30.467+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task extract_data ([Errno 13] Permission denied: '/opt/airflow/datasets/df.parquet'; 256)
[2025-04-10T01:59:30.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-10T01:59:30.559+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
